import fs from "node:fs";
import path from "node:path";

/*
 * Writes a Lean module holding the exact bytes of a hex file as a list literal.
 *
 * The Lean kernel can reduce a list of numerals quickly, but converting a
 * `String` to characters inside the kernel is very slow, so proofs about a
 * kernel's exact bytes read them from a generated literal instead of from
 * `include_str`. The binding to the file is kept by regeneration: the check
 * rebuilds this module from the hex file and requires it to be identical.
 *
 *   node tools/lean_bytes.mjs <file.hex> <Lean.Namespace> <out.lean>
 */

const [hexPath, namespace, outPath] = process.argv.slice(2);
const hex = fs.readFileSync(hexPath, "utf8").replace(/\s+/gu, "");
if (!/^([0-9a-f]{2})+$/u.test(hex)) {
  throw new Error(`${hexPath}: not lowercase hex octets`);
}
const bytes = hex.match(/../gu).map((pair) => parseInt(pair, 16));
// Only the file name goes into comments: a path can contain `/-`, which opens
// a nested Lean comment.
const name = path.basename(hexPath);
if (/\/-|-\//u.test(name)) throw new Error(`${name}: cannot appear in a Lean comment`);
const lines = [];
for (let i = 0; i < bytes.length; i += 16) {
  lines.push("  " + bytes.slice(i, i + 16).join(", "));
}
fs.writeFileSync(outPath, [
  `/- Generated by tools/lean_bytes.mjs from ${name}. Do not edit. -/`,
  `namespace ${namespace}`,
  "",
  `/-- The ${bytes.length} octets of \`${name}\`. -/`,
  "def exactBytes : List Nat := [",
  lines.join(",\n"),
  "]",
  "",
  `end ${namespace}`,
  "",
].join("\n"));
